language: ruby
rvm:
- 2.0.0
env:
- DB=postgres
before_script:
- psql -c 'create database trakehner_test;' -U postgres
script:
- RAILS_ENV=test bundle exec rake db:migrate --trace
- bundle exec rake db:test:prepare
- bundle exec rake
bundler_args: --binstubs=./bundler_stubs
deploy:
  provider: heroku
  api_key:
    secure: BYjmeJO+qU3PjNTCiMtylg1JKGv7fX7w65itowCCBQHsIYX2m/pCQA9vT4FwcKoo2qEcMFL35vbQs+kBLmHwOuNTthvCt1y+spxjz63UA9mbedUpNYXgI9Mp+b76FhMprZFxf3oVdVnJl5l9e/PxMnKlXBIU/wD4o2eHKdd9seM=
  app: trakehner-db
  on:
    repo: sprestage/trakehner-db
