language: ruby
rvm:
- 2.1.4
env:
  matrix:
  - DB=postgres
  global:
  - secure: nVSPHEdbh6qggmjNoagcpRi4sz6DZxrCVDHdrgc1WFLr5BcPKp1XwFgpMOdk184+d28CZLN8Nl3QGU16zUAwnSgYEK8Enzwj5rkhoMlxlaY1/lnC9yuwrk9fU/AX3qcF3XfkJTcHVK6q/i24O5kQhhZjBL/WEZBR1nLUMYqJgfw=
  - secure: gvatEx4Eh+2hOA06/1Hx6fknEFJB7NEhlTKz/+AIa0iQ1oFQua5Zsphv6hEI5oaoTn6cJ7igLDYvg3peBdktIhjpYh4G1iN33AfrLJR0tG56nXHrX9YB/VQhctDUCk0XA/+EcVIys24rPcu5NWqfTbswyUFxsMRFMO2qQO7Y7iw=
before_script:
- psql -c 'create database trakehner_test;' -U postgres
script:
- RAILS_ENV=test bundle exec rake db:migrate --trace
- bundle exec rake
bundler_args: "--binstubs=./bundler_stubs"
deploy:
  provider: heroku
  api_key:
    secure: TzSC/FvUTATklM19PYHkelaqp1xJNA4Jhvw67T211Yw6pMa+ZuAZaSYkQ3XRg3dmlDfLQxl4hTjQiox9MGjmXoNlwIXJ6B4Y61wemOYMhmI+Ju/UYkwWSZaUgRugB3uFi/cv2F36JtvtlD2X7Ti5UzrGjIJ0MU8FoAl5HexfwzM=
  app: trakehner-db
  on:
    repo: sprestage/trakehner-db
